### ISSUE TITLE
The list of SubTrees is not updated after adding new include from UI

### ISSUE THREAD

**Issue by OPerepadia** [BehaviorTree/Groot2#10]
**Describe the bug**
When adding new include from UI using "Browse for include" button, the subtrees from included xml are not loaded, even after saving and reloading file using "Reload" option in context menu.

**To Reproduce**
Add new include using "Browse for include" button. Subtrees from included file are not showing in Trees and Models view. Save, close and reopen main tree. Now the list of subtrees is updated.

**Expected behavior**
List of SubTrees is updated after adding new include from UI

**Desktop (please complete the following information):**
 - OS: Arch Linux
 - Version: Groot 0.4.0

**Comment by facontidavide** [comment]
This is fixed and it will be present in the next release
