### ISSUE TITLE
Highlight the port selected with the same name in all nodes

### ISSUE THREAD

**Issue by kyleYehh** [BehaviorTree/Groot2#11]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
When editing in Groot1, if a remapped port name is selected (by double clicking mouse), all other nodes' ports with the same remapped name will be highlighted. I really like this feature since it quickly shows nodes that use the same port. It is really convenient. However in Groot2, no highlight shows. It'd be great if we can re-have this feature.

**Comment by facontidavide** [comment]
This is already in the roadmap. Hopefully it will be implemented soon

**Comment by facontidavide** [comment]
done
