### ISSUE TITLE
Improve process of adding new nodes to the tree

### ISSUE THREAD

**Issue by OPerepadia** [BehaviorTree/Groot2#12]
**Is your feature request related to a problem? Please describe.**
Groot 1 had a convenient method of quickly adding new nodes from the context menu, where you just start typing the name and insert the node with a single click.

[Peek 2023-02-09 12-16.webm](https://user-images.githubusercontent.com/80095612/217784458-fe113f3b-6a4f-496c-b9f4-56ba904f1cba.webm)

**Describe the solution you'd like**
I have 2 suggestions how to improve searching and placing in Groot 2:
- add search menu, which can be accessed either by context menu like before, or launched by some keyboard shortcut.
- make all categories in 'Models' view to be expanded by default, so we don't have to manually unfold each category when searching nodes for the first time.

**Comment by facontidavide** [comment]
done
