### ISSUE TITLE
The application exits without a warning for unsaved changes.

### ISSUE THREAD

**Issue by marmik18** [BehaviorTree/Groot2#15]
**Describe the bug**
The application exits without a warning for unsaved changes.

**To Reproduce**
- Open Groot 2
- Create Empty File 
- Make some changes 
- Close the window 

**Expected behavior**
If there are any changes apart from the default template, the application should warn the user before exiting unsaved changes. 

**Desktop (please complete the following information):**
 - OS: Ubuntu
 - Version: 22.04
 - Arch: x86

**Comment by facontidavide** [comment]
we will fix that, thanks

**Comment by facontidavide** [comment]
Fixed
