### ISSUE TITLE
Includes are not loaded if xml doesn't contain BehaviorTree tag

### ISSUE THREAD

**Issue by OPerepadia** [BehaviorTree/Groot2#18]
**Describe the bug**
If included file doesn't contain any trees, it's includes are not loaded.

**To Reproduce**

Create top level tree:
```xml
<?xml version="1.0" encoding="UTF-8"?>
<root BTCPP_format="4">

  <include path="macros.xml"/>

  <BehaviorTree ID="MainTree">
    <SubTree ID="IncludedSubtree"/>
  </BehaviorTree>

</root>
```

Create `macros.xml`:
```xml
<?xml version="1.0" encoding="UTF-8"?>
<root BTCPP_format="4">

  <include path="macros_sim.xml"/>

<!-- <BehaviorTree ID="aaaaa">
    <AlwaysSuccess/>
  </BehaviorTree> -->

</root>
```

Create `macros_sim.xml`:
```xml
<?xml version="1.0" encoding="UTF-8"?>
<root BTCPP_format="4">

  <BehaviorTree ID="IncludedSubtree">
    <AlwaysSuccess/>
  </BehaviorTree>

</root>
```

The subtree `IncludedSubtree` is loaded only if the dummy tree in `macros.xml` is uncommented.

**Expected behavior**

Includes are loaded even if xml doesn't have any behavior trees.

**Comment by facontidavide** [comment]
fixed. Next version will include this change
