### ISSUE TITLE
Code execution cannot proceed becuase LexActivator.dll was not found

### ISSUE THREAD

**Issue by sjpritchard** [BehaviorTree/Groot2#19]
**Describe the bug**
Groot2 fails on start with "The code execution cannot proceed because LexActivator.dll was not found. Reinstalling the program may fix this problem"

**To Reproduce**

Clean installation of Groot2 0.5.0

**Expected behavior**
Groot2 should start normally

**Screenshots and videos**
Consider using a screen-recording application (for instance, https://www.screencapture.com/)

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Version 22H2

**Additional context**

**Comment by facontidavide** [comment]
Thanks a lot for reporting, my bad.

try downloading again here https://s3.us-west-1.amazonaws.com/download.behaviortree.dev/groot2_windows_installer/Groot2-0.5.0-windows-installer.exe

Link changed on the website too
