### ISSUE TITLE
Support `ScriptCondition` condition node

### ISSUE THREAD

**Issue by kd-ufr** [BehaviorTree/Groot2#22]
**Is your feature request related to a problem? Please describe.**
In BT.CPP v4.3 the `ScriptCondition` condition node was added, but it is not supported by Groot 2 (0.9.0).

**Describe the solution you'd like**
It'd be great if this could  be added to Groot 2 - I'm sure a lot of people would like to use it but aren't aware of its existance.

**Describe alternatives you've considered**
NA

**Additional context**
NA

Thank you in advance :)

**Comment by facontidavide** [comment]
To be added in next release
