### ISSUE TITLE
More colour palate options

### ISSUE THREAD

**Issue by kd-ufr** [BehaviorTree/Groot2#24]
**Is your feature request related to a problem? Please describe.**
I find the new colour palate for trees in version 1.0.0 very noisy and distracting across a large tree (especially the gradient on nodes in dark mode).

**Describe the solution you'd like**
Please give an option to go back to the colour scheme of 0.9.0, or an option to downgrade versions of groot2. 
Many thanks.

**Additional context**
Dark mode in 1.0.0:
![image](https://github.com/BehaviorTree/Groot2/assets/118779546/62d3e8d0-072c-4200-81cf-34ec3430cdb2)

Light mode in 1.0.0:
![image](https://github.com/BehaviorTree/Groot2/assets/118779546/d708e29c-4ebf-48e9-ae92-9df6c8181a07)

**Comment by facontidavide** [comment]
Sorry to hear that.
Of course different people will have different taste.

I think a good solution would be to add a custom palette that the user can tune to their liking.

I will consider adding that option in the next release.

**Comment by kd-ufr** [comment]
That sounds like a good solution, looking forward to it :)

**Comment by facontidavide** [comment]
done
