### ISSUE TITLE
Box sometimes do not contain the whole last field when importing from older Groot 

### ISSUE THREAD

**Issue by Kotochleb** [BehaviorTree/Groot2#25]
**Describe the bug**
When I opened, the project I was working on about March/April this year with older release of Groot last section of boxes were outside of the scope of the general box. It is hard for me to explain, that is why I am attaching a screenshot. When I clicked to rearrange the tree to be horizontal, and then again vertical, everything was fine. The problem did not appear in previous Groot in the times of old color scheme.

Anyway, this is a minor issue. Just mentioning that is appeared in my case.

**To Reproduce**
Here are links to the project that showed this issue. Simply opening it should suffice:
- [project]( https://github.com/husarion/panther_ros/blob/1ab005918952d6b83b7975ef20531473c9bba2c2/panther_manager/config/Panther12BT.btproj)
- [subtree 1](https://github.com/husarion/panther_ros/blob/1ab005918952d6b83b7975ef20531473c9bba2c2/panther_manager/config/lights.xml)
-  [subtree 2](https://github.com/husarion/panther_ros/blob/1ab005918952d6b83b7975ef20531473c9bba2c2/panther_manager/config/safety.xml)
-  [subtree 3](https://github.com/husarion/panther_ros/blob/1ab005918952d6b83b7975ef20531473c9bba2c2/panther_manager/config/shutdown.xml)

**Expected behavior**
The last section of the given box is contained within it.

**Screenshots and videos**
![Screenshot from 2023-07-13 12-25-35](https://github.com/BehaviorTree/Groot2/assets/49921081/6497a9e9-eae9-4e03-9565-f20efa04323e)

**Desktop (please complete the following information):**
- Ubuntu 20.04, Groot 2 v1.0.1, AppImage
- Ubuntu 22.04 (seems to work fine)

**Comment by facontidavide** [comment]
Should be fixed in the next version, to be released soon
