### ISSUE TITLE
Log mode transitions table - increase filtering capability

### ISSUE THREAD

**Issue by kd-ufr** [BehaviorTree/Groot2#26]
**Is your feature request related to a problem? Please describe.**
It is hard to read the transitions table in log mode if a tree has reactive sequences - the transitions are filled by the continual IDLE->SUCCESS->IDLE->SUCCESS of the conditional child nodes. You have to sift through this noise to find the node transitions of interest.

**Describe the solution you'd like**
Some things that would improve the readability of the transitions table:
- filtering OUT based on node name (eg !Node1)
- filtering IN multiple node names (eg Node2 && Node3)

This achieves a very similar result to what was requested here (https://github.com/BehaviorTree/BehaviorTree.CPP/issues/559), and would be a great draw card for Groot2 Pro. 

**Describe alternatives you've considered**
The 'Hide transition to IDLE' option does cut this down a lot. However, if you have a reactive sequence with 2 conditions and 1 action as children, the transitions panel is 2/3rds noise and only 1/3rd helpful information. 

**Additional context**
Groot2 v1.0.1

**Comment by facontidavide** [comment]
Hi, thanks for your suggestions :smiley: 

The Filter IN/OUT is a very good idea, I will add to our roadmap and we will probably be able to work on this in August.

About the comment "transitions panel is 2/3rds noise and only 1/3rd helpful information.", that depends on the information you need. For somebody is noise, for others is the information they need to know if Reactive is working as intended.

**Comment by kd-ufr** [comment]
That's a fair point. Looking forward to seeing it implemented :)

**Comment by facontidavide** [comment]
Implemented in 1.2, to be released soon
