### ISSUE TITLE
Improve multi-file workflow

### ISSUE THREAD

**Issue by lukicdarkoo** [BehaviorTree/Groot2#3]
**Is your feature request related to a problem? Please describe.**
Typically, we have multiple "missions" that we choose depending on the robot or use case. Therefore, an ideal structure would be:
- `skills.xml`: common subtrees for all missions
- `models.xml`: declarations of all available nodes
- `mission_1.xml`: an actual mission that we load at runtime depending on arguments
- `mission_2.xml`: an actual mission that we load at runtime depending on arguments

Each mission file would include `skills.xml` and `models.xml`.

There are two issues with Groot:
- Groot doesn't recognize the includes. I have to import each file individually.
- Includes are recognized when I create a high-level `.btproj` file that includes all `.xml` files. However, there are two problems with this approach:
  - If I save a `.xml` file within the `.btproj` project it inserts all node declarations to the `.xml` file. There is no need to have node declarations in each `.xml` file.
  - I need either to create a `.btproj` project for each mission or we will see irrelevant trees (either of which is undesirable).

**Describe the solution you'd like**
Ideally, we should be able to work with `.xml` files directly (without `.btproj` files) and Groot should be able to follow includes and recognize where the node declarations are stored. At least, Groot should not insert node declarations in XML files if the declarations are already present in the `.btproj` file.

**Additional context**
It is possible I use Groot 2 in the wrong way. I would appreciate if you could share a recommended workflow.

**Comment by facontidavide** [comment]
Hi Darko,

There is nothing that prevent you from achieving your goal and, if there is, I will be happy to help you!

I think that you just need to slightly adapt the way you used to work and use the new one instead. Some comments:

- **Repeated Models in multiple files**: the idea is that the **btproj** should contains all the model, similarly to your `models.xml`. I replicate those models inside each individual file to make possible to individually open that file. There is no drawback to it, as long as the models are consistent.

- **Groot doesn't recognize the tag "include"**: I should fix this, hopefully in beta 4.

The big problem, in my opinion, is how to manage those includes AFTER, when the XML is modified and saved.
Should the user be able to add/modify/remove includes inside Groot?

The new suggested workflow is to STOP using **\<include\>** and use the `btproj ` instead.
You do not necessary need to create one file per mission, if you follow the design pattern described in [tutorial 7](https://www.behaviortree.dev/docs/tutorial-basics/tutorial_07_multiple_xml)

- use `registerBehaviorTreeFromFile `once.
- create the tree at runtime with the specific mission with `createTree`.

What do you think?

**Comment by lukicdarkoo** [comment]
Hi Davide, thank you for the quick response.

> * **Repeated Models in multiple files**: the idea is that the **btproj** should contains all the model, similarly to your `models.xml`. I replicate those models inside each individual file to make possible to individually open that file. There is no drawback to it, as long as the models are consistent.

I assumed it was done on purpose. In a way it makes sense, but:
- it creates a big diff, reviewing PRs is a bit harder
- if we change a declaration there are more places to reflect the change
- in case we textually edit files (e.g. we edit trees visually and textually) then there is additional work necessary to keep everything consistent

> The big problem, in my opinion, is how to manage those includes AFTER, when the XML is modified and saved.
> Should the user be able to add/modify/remove includes inside Groot?

I see, this is a tough one, I am not sure what is the best approach. A few things to keep in mind:
- Without the `<include>` tag we have to define dependencies in two places, C++ and `.btproj`. With the properly processed `<include>` tag there would be no need for `.btproj` files, `.xml` would be enough.
- With the `<include>` tag it would be easier to isolate multiple non-related BTs (in case we are picking which `.xml` file to load).
- In C++ it is easier to define where `.xml` files are located. I am afraid that managing any non-relative path in XML is "hacky".

More users should be involved in this one.

In general, I believe it is critical Groot 2 is designed such that BTs can easily be manipulated textually as well.

**Comment by facontidavide** [comment]
> in case we textually edit files (e.g. we edit trees visually and textually) then there is additional work necessary to keep everything consistent.

This is something I want to fix! I would like to go into more details with you about the specific cases that are not related to **include**.

> if we change a declaration there are more places to reflect the change

When you say "declaration" you mean the **NodeModel**? Remember that those are not supposed to be modified by hand, in general, but to be autogenerated by you C++ code.

> Without the <include> tag we have to define dependencies in two places, C++ and .btproj.

Why? I don't think that is thew case. You should be able to define them only in the  .btproj. 
Can you provide a practical example?

> In C++ it is easier to define where .xml files are located. I am afraid that managing any non-relative path in XML is "hacky".

True. Ideally Groot2 should include in "Preferences" (to be added) a table of "Search directories" to use to resolve the includes. This will cover most of the cases, in my opinion.

Summarizing, I am happy to arrange a meeting with you to discuss these issues in more details.
I think that the ideal solution is for you to slightly change your workflow and I also have changes to add to Groot2, probably.

**Comment by facontidavide** [comment]
Hi,

please try Beta 4 https://www.behaviortree.dev/blog/beta4
It has includes and it should be exactly what you asked for.
