### ISSUE TITLE
Crash Triggered by Renaming Subtree with Port Mappings

### ISSUE THREAD

**Issue by moccajoghurt** [BehaviorTree/Groot2#31]
I am sorry to report again but after the release I still have the same bug.

1. Create a Subtree: Begin by crafting a new subtree.
2. Integrate Subtree: Incorporate the newly created subtree into another tree.
3. Add Port Remapping: Apply a port remapping to the created subtree.
4. Rename the Subtree: Modify the original subtree's name.
5. Result: Groot2 crashes upon renaming.

https://github.com/BehaviorTree/Groot2/assets/2771765/955cd750-053c-4d77-84ae-a887507013bd

**Comment by facontidavide** [comment]
I just uploaded a new version. I have the feeling that the binary was wrong. Can you please try this one?

https://s3.us-west-1.amazonaws.com/download.behaviortree.dev/groot2_linux_installer/Groot2-v1.2.0-x86_64.AppImage

**Comment by moccajoghurt** [comment]
I am using the windows version. I can't test on linux at the moment.
When I download the windows version via this link:
https://s3.us-west-1.amazonaws.com/download.behaviortree.dev/groot2_windows_installer/Groot2-1.2.0-windows-installer.exe
The same bug occurs.

**Comment by facontidavide** [comment]
Windows version is still broken, I will tell you when to download it again

**Comment by moccajoghurt** [comment]
With version 1.3.1 I the issue seems to be gone completely. Thank you!
