### ISSUE TITLE
Can't deactivate trial license

### ISSUE THREAD

**Issue by antonkesy** [BehaviorTree/Groot2#34]
**Describe the bug**
I'm getting an error window "Failed" when trying to deactivate my trial license in the preferences for Groot2
The trial is not canceled

**To Reproduce**

- Start pro trial license in Preferences -> License
- (restart)
- Press "Deactivate" in Preferences -> License

**Expected behavior**
- no error message
- Trial to not be active anymore and only have access to non-Pro version

**Screenshots and videos**
![Screenshot from Groot2 preferences with error window](https://github.com/BehaviorTree/Groot2/assets/25124866/44c9613d-d3da-4f05-b071-3f684d280ecc)

**Desktop (please complete the following information):**
- OS: Ubuntu 22.04.3 LTS x86_64 
- Groot2 v1.3.1 x86_64 AppImage

**Additional context**
Terminal output of running Groot2.AppImage
```
Info: Wed Sep 27 16:33:37 2023 - Running free version
loaded Parser plugin:  "libFileLogger2Parser.so"
loaded Writer plugin:  "libFileLogger2Writer.so"
loaded Parser plugin:  "libFlatbuffersParser.so"
loaded Parser plugin:  "libSQLiteParser.so"
current version:  "1.3.1"
latest online version:  "1.3.1"
```

**Comment by facontidavide** [comment]
thanks for reporting. I will fix that ASAP

**Comment by facontidavide** [comment]
Sorry, but once started, the trial can not be cancelled
