### ISSUE TITLE
Dark theme

### ISSUE THREAD

**Issue by simchanu29** [BehaviorTree/Groot2#4]
**Is your feature request related to a problem? Please describe.**
![image](https://user-images.githubusercontent.com/10176249/210328931-840f5b0d-abf5-4079-9797-9f0b338d71d1.png)
![image](https://user-images.githubusercontent.com/10176249/210329148-9525fc93-8efb-4c77-9770-441e2f37f66e.png)
On a dark desktop theme, some text are difficult to read

**Describe the solution you'd like**
A dark theme

**Additional context**
OS : Ubuntu 20
Desktop : Plasma 5
Theme : Yaru Dark

**Comment by facontidavide** [comment]
Thanks for reporting, I will address this in future beta release, hopefully by the end of the next week

**Comment by facontidavide** [comment]
Fixed in **beta 4.** I will push it soon

**Comment by facontidavide** [comment]
Should be fixed in beta 4. Let me know if the problem persists
