### ISSUE TITLE
Identify order of child nodes

### ISSUE THREAD

**Issue by ernestmc** [BehaviorTree/Groot2#43]
**Is your feature request related to a problem? Please describe.**
In many nodes like Sequence or WhileDoElse the order of child nodes is important because it relates to order of execution or function. 
In the editor if the nodes are re-arranged the order/function of each one is lost and there is no evident way of telling which is which.

**Describe the solution you'd like**
Numbers could be associated and displayed next to each edge connecting to the child node. This way it is always evident which node is which.

**Describe alternatives you've considered**
-

**Additional context**
-

**Comment by facontidavide** [comment]
Thanks for the suggestion :slightly_smiling_face: , but I believe that the current approach is correct and I am not planning to change it.
