### ISSUE TITLE
Parameter order is ignored when opening/saving .xml files

### ISSUE THREAD

**Issue by OPerepadia** [BehaviorTree/Groot2#5]
**Is your feature request related to a problem? Please describe.**
When opening .xml files which contain nodes with multiple input parameters, Groot shows them in a different order (it seems in alphabetical, but I'm not sure).
In a same way, when saving mission files in Groot, the order of parameters in .xml file is changed.

**Describe the solution you'd like**
It would be good if Groot was able to keep the original order of input parameters. This would make it possible to put most commonly used parameters first, and add less used ones in the end of the list. Also, some parameters may be related to each other, so it make sense to keep them close to each other.

**Comment by facontidavide** [comment]
Indeed the order is:

- input / output / INOUT groups.
- each group alphabetically.

I understand your suggestion and I will think about it, BUT the specific order can ONLY be set in the `\<TreeNodesModel\>` section of the XML, it can not be deducted from the particular instance in `\<BehaviorTree\>`

**Comment by OPerepadia** [comment]
> BUT the specific order can ONLY be set in the `<TreeNodesModel>` section of the XML

Yes, exactly, this should be enough for our use case.

**Comment by facontidavide** [comment]
fixed
