### ISSUE TITLE
UI improvement proposal

### ISSUE THREAD

**Issue by simchanu29** [BehaviorTree/Groot2#6]
Following our discussion, I list here the UI improvements we discussed. This is a backlog for possible future improvements.

### Editor UI
- Be able to move/reorganize tabs by click and move
- On Ubuntu 20/Plasma 5 , the filepicker used is not the same between Groot2 and Groot (1). I prefer the one used in Groot. 
- Autocompletion in ports based on existing ports value

**Comment by facontidavide** [comment]
1. Moving tabs already fixed, will be present in the next beta release
2. There is little I can do about that, it is probably a change in Qt6 vs Qt 5
3. great idea about autocompletion. I will add it to the roadmap

**Comment by facontidavide** [comment]
Hi, please check [Beta4](https://www.behaviortree.dev/blog/beta4).

It fixes moving tabs.

**Comment by facontidavide** [comment]
I will close this and add autocompletion of ports to the roadmap. thanks
