### ISSUE TITLE
High cpu usage when XML editor is active [beta-4]

### ISSUE THREAD

**Issue by OPerepadia** [BehaviorTree/Groot2#8]
**Describe the bug**
High cpu usage when XML editor is active

**To Reproduce**
Open any XML file, for example `tutorial_01_simple_tree`, and see cpu usage increasing substantially. When tree is closed, cpu usage returns back to normal.

**Screenshots and videos**
![Screenshot_20230202_123659](https://user-images.githubusercontent.com/80095612/216302546-483202c1-c52f-41dc-942e-f0a409939148.png)

**Desktop (please complete the following information):**
 - OS: Arch Linux/Ubuntu 22.04
 - Groot 0.4.0 (beta-4, 2023-01-28) AppImage

**Comment by facontidavide** [comment]
thanks for reporting, I will look at this today

**Comment by facontidavide** [comment]
Problem found! I will probably release beta 5 over the weekend, with the fix.

Thanks a lot !

**Comment by facontidavide** [comment]
Fixed in beta 5. Thanks again for reporting
