### ISSUE TITLE
Buggy ports editing

### ISSUE THREAD

**Issue by kubakaminski** [BehaviorTree/Groot2#9]
**Describe the bug**
When editing text in a node's port, the text coursor jumps to the end of the text after every typed character.

**To Reproduce**

Create a node with a port, place it on a tree. In the port field write some text and try to delete or add some characters in the middle of the word.

**Screenshots and videos**
https://imgur.com/a/ELNcaUV

**Desktop (please complete the following information):**
 - OS: Ubuntu 20.04
 - Version: Groot 0.4

**Comment by facontidavide** [comment]
Hi @kubakaminski I am sorry that you are experiencing this issue.

Thanks a lot for reporting. I will fix this today and release immediately a new version
